require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'config/boot.rb'
    - 'config/puma.rb'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

RSpec/MultipleExpectations:
  Max: 3

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - spec/**/*

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - app/components/**/*

RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - spec/system/**/*
