require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  # - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'config/boot.rb'
    - 'config/puma.rb'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'tmp/**/*'
    - 'config/initializers/simple_form.rb'

Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - spec/**/*

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - app/components/**/*

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Style/ClassAndModuleChildren:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table

# RSpec/ExampleLength:
#   Enabled: true
#   Exclude:
#     - spec/system/**/*

# RSpec/MultipleExpectations:
#   Max: 3
