class SigninForm
  @user: User?

  attr_reader email: String?
  attr_reader password: String?

  def initialize: (options: ActionController::Parameters) -> void
  def incorrect_user_or_password?: -> bool
  def user_error: -> String

  private

  def user: () -> User?
end
